/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DayOfWeek = { 'Saturday' : null } |
  { 'Thursday' : null } |
  { 'Sunday' : null } |
  { 'Tuesday' : null } |
  { 'Friday' : null } |
  { 'Wednesday' : null } |
  { 'Monday' : null };
export type ExternalBlob = Uint8Array;
export interface OCRResult {
  'day' : DayOfWeek,
  'endHour' : bigint,
  'subject' : string,
  'endMinute' : bigint,
  'startMinute' : bigint,
  'location' : [] | [string],
  'startHour' : bigint,
}
export interface Task {
  'day' : DayOfWeek,
  'subject' : string,
  'completed' : boolean,
  'inProgress' : boolean,
  'location' : [] | [string],
  'timeSlot' : TimeSlot,
}
export interface TimeSlot {
  'endHour' : bigint,
  'endMinute' : bigint,
  'startMinute' : bigint,
  'startHour' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getAllTasks' : ActorMethod<[], Array<[DayOfWeek, Task]>>,
  'getCurrentTask' : ActorMethod<[], [] | [Task]>,
  'getTaskCompletionStatus' : ActorMethod<[DayOfWeek, bigint], boolean>,
  'getTasksByDay' : ActorMethod<[DayOfWeek], Array<Task>>,
  'getTimeRemainingForTask' : ActorMethod<[DayOfWeek, bigint], [] | [bigint]>,
  'getTimetableImage' : ActorMethod<[], [] | [ExternalBlob]>,
  'getWeeklySchedule' : ActorMethod<[], Array<[DayOfWeek, Array<Task>]>>,
  'markTaskInProgress' : ActorMethod<[DayOfWeek, bigint], undefined>,
  'processOCRResult' : ActorMethod<[Array<OCRResult>], undefined>,
  'toggleTaskCompletion' : ActorMethod<[DayOfWeek, bigint], undefined>,
  'updateTimetableImage' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];