/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DayOfWeek = IDL.Variant({
  'Saturday' : IDL.Null,
  'Thursday' : IDL.Null,
  'Sunday' : IDL.Null,
  'Tuesday' : IDL.Null,
  'Friday' : IDL.Null,
  'Wednesday' : IDL.Null,
  'Monday' : IDL.Null,
});
export const TimeSlot = IDL.Record({
  'endHour' : IDL.Nat,
  'endMinute' : IDL.Nat,
  'startMinute' : IDL.Nat,
  'startHour' : IDL.Nat,
});
export const Task = IDL.Record({
  'day' : DayOfWeek,
  'subject' : IDL.Text,
  'completed' : IDL.Bool,
  'inProgress' : IDL.Bool,
  'location' : IDL.Opt(IDL.Text),
  'timeSlot' : TimeSlot,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const OCRResult = IDL.Record({
  'day' : DayOfWeek,
  'endHour' : IDL.Nat,
  'subject' : IDL.Text,
  'endMinute' : IDL.Nat,
  'startMinute' : IDL.Nat,
  'location' : IDL.Opt(IDL.Text),
  'startHour' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllTasks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DayOfWeek, Task))],
      ['query'],
    ),
  'getCurrentTask' : IDL.Func([], [IDL.Opt(Task)], ['query']),
  'getTaskCompletionStatus' : IDL.Func(
      [DayOfWeek, IDL.Nat],
      [IDL.Bool],
      ['query'],
    ),
  'getTasksByDay' : IDL.Func([DayOfWeek], [IDL.Vec(Task)], ['query']),
  'getTimeRemainingForTask' : IDL.Func(
      [DayOfWeek, IDL.Nat],
      [IDL.Opt(IDL.Int)],
      ['query'],
    ),
  'getTimetableImage' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getWeeklySchedule' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DayOfWeek, IDL.Vec(Task)))],
      ['query'],
    ),
  'markTaskInProgress' : IDL.Func([DayOfWeek, IDL.Nat], [], []),
  'processOCRResult' : IDL.Func([IDL.Vec(OCRResult)], [], []),
  'toggleTaskCompletion' : IDL.Func([DayOfWeek, IDL.Nat], [], []),
  'updateTimetableImage' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DayOfWeek = IDL.Variant({
    'Saturday' : IDL.Null,
    'Thursday' : IDL.Null,
    'Sunday' : IDL.Null,
    'Tuesday' : IDL.Null,
    'Friday' : IDL.Null,
    'Wednesday' : IDL.Null,
    'Monday' : IDL.Null,
  });
  const TimeSlot = IDL.Record({
    'endHour' : IDL.Nat,
    'endMinute' : IDL.Nat,
    'startMinute' : IDL.Nat,
    'startHour' : IDL.Nat,
  });
  const Task = IDL.Record({
    'day' : DayOfWeek,
    'subject' : IDL.Text,
    'completed' : IDL.Bool,
    'inProgress' : IDL.Bool,
    'location' : IDL.Opt(IDL.Text),
    'timeSlot' : TimeSlot,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const OCRResult = IDL.Record({
    'day' : DayOfWeek,
    'endHour' : IDL.Nat,
    'subject' : IDL.Text,
    'endMinute' : IDL.Nat,
    'startMinute' : IDL.Nat,
    'location' : IDL.Opt(IDL.Text),
    'startHour' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllTasks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DayOfWeek, Task))],
        ['query'],
      ),
    'getCurrentTask' : IDL.Func([], [IDL.Opt(Task)], ['query']),
    'getTaskCompletionStatus' : IDL.Func(
        [DayOfWeek, IDL.Nat],
        [IDL.Bool],
        ['query'],
      ),
    'getTasksByDay' : IDL.Func([DayOfWeek], [IDL.Vec(Task)], ['query']),
    'getTimeRemainingForTask' : IDL.Func(
        [DayOfWeek, IDL.Nat],
        [IDL.Opt(IDL.Int)],
        ['query'],
      ),
    'getTimetableImage' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getWeeklySchedule' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DayOfWeek, IDL.Vec(Task)))],
        ['query'],
      ),
    'markTaskInProgress' : IDL.Func([DayOfWeek, IDL.Nat], [], []),
    'processOCRResult' : IDL.Func([IDL.Vec(OCRResult)], [], []),
    'toggleTaskCompletion' : IDL.Func([DayOfWeek, IDL.Nat], [], []),
    'updateTimetableImage' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };